name: build

on:
  push:
    branches:
      - master
    tags:
      - '**'
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    name: Build with JDK ${{matrix.java}}

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-java@v1
        name: Setup JDK ${{matrix.java}}
        with:
          java-version: ${{matrix.java}}

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Maven build
        run: mvn -B verify package --file pom.xml

      - name: Generate Coveralls File
        if: matrix.java == '17'
        run: mvn -B coveralls:report -Pcoverage -DdryRun=true

      - name: Coveralls Analysis
        if: matrix.java == '17'
        uses: MikeEdgar/github-action@raw_coverage_file
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-file: ./target/coveralls.json
          coverage-format: raw

  javadoc:
    runs-on: ubuntu-latest
    name: Verify JavaDocs

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Generate JavaDocs
        run: mvn -B verify javadoc:javadoc --file pom.xml

  quality:
    if: ${{ github.repository == 'xlate/validators' && github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    name: Verify Quality

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow --tags --force

      - uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
